Repository HanHwa-Team1-Final-Project/MOIM-FE, pull requests merged in 2024-04, with the labels that each got.

#7 [Feat] 회원가입 화면 구현(#6)
  src/assets/image_1.png
  src/components/HelloWorld.vue
  src/main.js
  src/router/index.js
  src/views/LoginView.vue
  src/views/RegisterView.vue
Labels: 프론트-개발

#10 Feat/login - 로그인 외 기타 기능 추가
  src/App.vue
  src/router/index.js
  src/views/LoginView.vue
  src/views/RegisterView.vue
Labels: 프론트-개발

#11 Eunji/eisenhower matrix 5
  package-lock.json
  package.json
  src/components/MainPage.vue
  src/components/layout/AppSideBar.vue
  src/router/index.js
  src/views/EisenhowerMatrix.vue
Labels: 프론트-개발

#13 [Feat] 일정 생성 기능
  package-lock.json
  package.json
  src/App.vue
  src/components/MainPage.vue
  src/components/layout/AppHeader.vue
  src/components/layout/AppSideBar.vue
  src/main.js
  src/pages/event/EventDialog.vue
  src/router/index.js
  src/stores/index.js
  src/views/CalendarComponent.vue
  src/views/EventCreate.vue
  src/views/TestView.vue
Labels: 프론트-개발

#16 [Feat] 로그인 관련 기능 개발(#15)
  src/components/Oauth2Redirect.vue
  src/main.js
  src/plugins/tokenPlugin.js
  src/router/index.js
  src/views/EisenhowerMatrix.vue
  src/views/LoginView.vue
Labels: 기타, 프론트-개발

#18 [Feat] 공통 다이얼로그 생성
  src/components/CommonDialog.vue
  src/components/layout/AppSideBar.vue
  src/main.js
  src/router/index.js
  src/views/DialogTestView.vue
  src/views/EventCreate.vue
  src/views/TestView.vue
Labels: 프론트-개발

#23 Eunji/eisenhower matix 22
  package-lock.json
  package.json
  src/views/EisenhowerMatrix.vue
Labels: 프론트-개발

#26 Qoth/full calendar
  package-lock.json
  package.json
  src/components/layout/AppSideBar.vue
  src/pages/event/EventDetailDialog.vue
  src/pages/event/EventDialog.vue
  src/router/index.js
  src/views/FullCalendarComponent.vue
Labels: 프론트-개발

#28 Jaeseok/fix search
  package-lock.json
  package.json
  src/components/layout/AppHeader.vue
  src/pages/search/EventDetail.vue
  src/pages/search/SearchResults.vue
  src/router/index.js
  src/stores/searchStore.js
  src/utils/common.js
  src/utils/date-utils.js
Labels: 버그, 프론트-개발

#30 [Feat] 일정 상세 조회에서 파일 다운로드 기능 추가 #29
  src/components/layout/AppHeader.vue
  src/pages/search/EventDetail.vue
  src/pages/search/SearchResults.vue
Labels: 버그, 프론트-개발

#39 검색한 이벤트 삭제, 수정
  src/components/UpdateEvent.vue
  src/pages/search/DeleteRepeatEvent.vue
  src/pages/search/EventDetail.vue
  src/pages/search/SearchResults.vue
  src/router/index.js
  src/stores/updateEventStore.js
  src/views/DialogTestView.vue
Labels: 버그, 프론트-개발

#43 일정 수정 기능 완성
  src/components/UpdateEvent.vue
  src/components/layout/AppSideBar.vue
  src/pages/search/EventDetail.vue
  src/views/FullCalendarComponent.vue
Labels: 버그, 프론트-개발

#35 [Fix/login] 만료된 Access Token 재발급 안되는 이슈 해결(#34)
  src/axios/index.js
  src/main.js
  src/pages/event/EventDialog.vue
  src/plugins/tokenPlugin.js
  src/views/LoginView.vue
Labels: 버그, 프론트-개발

#45 axiosInstance 교체 및 로그인 페이지 진입 이슈 해결
  src/components/UpdateEvent.vue
  src/components/layout/AppHeader.vue
  src/components/layout/AppSideBar.vue
  src/main.js
  src/pages/event/EventDetailDialog.vue
  src/pages/event/EventDialog.vue
  src/pages/moim/MoimDialog.vue
  src/pages/search/DeleteRepeatEvent.vue
  src/pages/search/EventDetail.vue
  src/router/index.js
  src/views/CalendarComponent.vue
  src/views/EisenhowerMatrix.vue
  src/views/FullCalendarComponent.vue
  src/views/LoginView.vue
  src/views/RegisterView.vue
Labels: 버그, 프론트-개발

#49 [Refactor] 아이젠하워 매트릭스 화면 수정
  src/components/layout/AppHeader.vue
  src/components/layout/AppSideBar.vue
  src/pages/eisenhower/EisenhowerMatrix.vue
  src/router/index.js
  src/views/EisenhowerMatrix.vue
Labels: 프론트-개발

#67 [Feat] 국경일 연동
  src/App.vue
  src/components/MainPage.vue
  src/components/layout/AppHeader.vue
  src/main.js
  src/pages/search/SearchResults.vue
  src/style/gradientBackground.scss
  src/style/loginViewStyle.scss
  src/utils/animations.js
  src/views/FullCalendarComponent.vue
Labels: 프론트-개발

#74 로그인 화면 디자인 수정
  img/weekly_calendar.png
  public/img/Google__G__logo.svg
  public/index.html
  src/App.vue
  src/components/GoogleLogo.vue
  src/style/gradientBackground.css
  src/style/gradientBackground.css.map
  src/style/loginViewStyle.css
  src/style/loginViewStyle.css.map
  src/views/LoginView.vue
  src/views/RegisterView.vue
Labels: 프론트-개발

#76 [Feat/Auth] 구글, 카카오 로그인 연동 / 로그아웃 구현
  src/components/Oauth2Redirect.vue
  src/pages/myPage/MyPageDialog.vue
  src/views/LoginView.vue
Labels: 버그, 프론트-개발
